
var emo = [];
emo.push(/:Like:/gi);
emo.push(/:BigGrinGrinningSmiling:/gi);
emo.push(/:CryingTearsRiver:/gi);
emo.push(/:Pokerface:/gi);
emo.push(/:LikeLikedSupportThumbs:/gi);
emo.push(/:Sad:/gi);
emo.push(/:Blush:/gi);
emo.push(/:Evil:/gi);
emo.push(/:CheckerSucces:/gi);
emo.push(/:Confused:/gi);
emo.push(/:CoolSunglasses:/gi);
emo.push(/:Crazy:/gi);
emo.push(/:Crying:/gi);
emo.push(/:DevilDevilishEvil:/gi);
emo.push(/:Disappointed:/gi);
emo.push(/:DisappointedEyeRollMeme:/gi);
emo.push(/:DisappointmentDisappoint:/gi);
emo.push(/:DisappointmentDisappointed:/gi);
emo.push(/:EvilPlanAngry:/gi);
emo.push(/:FlirtySmile:/gi);
emo.push(/:ForgivePityPoorSorry:/gi);
emo.push(/:GeekNerd:/gi);
emo.push(/:HeartsLoveLoving:/gi);
emo.push(/:HugHuggingOffering:/gi);
emo.push(/:IdeaGenius:/gi);
emo.push(/:JawDroppedShock:/gi);
emo.push(/:KissKissingLipsXoxo:/gi);
emo.push(/:LoveGiftGive:/gi);
emo.push(/:MadRedBoiling:/gi);
emo.push(/:Neutral:/gi);
emo.push(/:OffendedBroken:/gi);
emo.push(/:RoseGiftLove:/gi);
emo.push(/:ShockedScreamingScream:/gi);
emo.push(/:ShrugShrugging:/gi);
emo.push(/:Smiling:/gi);
emo.push(/:StinkyDisgustingFlies:/gi);
emo.push(/:Sweating:/gi);
emo.push(/:ThinkingConfusedShrug:/gi);
emo.push(/:TiredSleepy:/gi);
emo.push(/:TongueTease:/gi);
emo.push(/:UnSureSuspicious:/gi);
emo.push(/:HeartLoveValentine:/gi);


var emoValue = [];
emoValue.push(":Like:");
emoValue.push(":BigGrinGrinningSmiling:");
emoValue.push(":CryingTearsRiver:");
emoValue.push(":Pokerface:");
emoValue.push(":LikeLikedSupportThumbs:");
emoValue.push(":Sad:");
emoValue.push(":Blush:");
emoValue.push(":Evil:");
emoValue.push(":CheckerSucces:");
emoValue.push(":Confused:");
emoValue.push(":CoolSunglasses:");
emoValue.push(":Crazy:");
emoValue.push(":Crying:");
emoValue.push(":DevilDevilishEvil:");
emoValue.push(":Disappointed:");
emoValue.push(":DisappointedEyeRollMeme:");
emoValue.push(":DisappointmentDisappoint:");
emoValue.push(":DisappointmentDisappointed:");
emoValue.push(":EvilPlanAngry:");
emoValue.push(":FlirtySmile:");
emoValue.push(":ForgivePityPoorSorry:");
emoValue.push(":GeekNerd:");
emoValue.push(":HeartsLoveLoving:");
emoValue.push(":HugHuggingOffering:");
emoValue.push(":IdeaGenius:");
emoValue.push(":JawDroppedShock:");
emoValue.push(":KissKissingLipsXoxo:");
emoValue.push(":LoveGiftGive:");
emoValue.push(":MadRedBoiling:");
emoValue.push(":Neutral:");
emoValue.push(":OffendedBroken:");
emoValue.push(":RoseGiftLove:");
emoValue.push(":ShockedScreamingScream:");
emoValue.push(":ShrugShrugging:");
emoValue.push(":Smiling:");
emoValue.push(":StinkyDisgustingFlies:");
emoValue.push(":Sweating:");
emoValue.push(":ThinkingConfusedShrug:");
emoValue.push(":TiredSleepy:");
emoValue.push(":TongueTease:");
emoValue.push(":UnSureSuspicious:");
emoValue.push(":HeartLoveValentine:");



var emoImg = [];
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Like.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/BigGrinGrinningSmiling.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/CryingTearsRiver.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Pokerface.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/LikeLikedSupportThumbs.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Sad.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Blush.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Evil.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/CheckerSucces.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Confused.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/CoolSunglasses.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Crazy.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Crying.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/DevilDevilishEvil.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Disappointed.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/DisappointedEyeRollMeme.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/DisappointmentDisappoint.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/DisappointmentDisappointed.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/EvilPlanAngry.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/FlirtySmile.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/ForgivePityPoorSorry.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/GeekNerd.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/HeartsLoveLoving.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/HugHuggingOffering.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/IdeaGenius.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/JawDroppedShock.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/KissKissingLipsXoxo.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/LoveGiftGive.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/MadRedBoiling.png\" height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Neutral.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/OffendedBroken.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/RoseGiftLove.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/ShockedScreamingScream.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/ShrugShrugging.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Smiling.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/StinkyDisgustingFlies.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/Sweating.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/ThinkingConfusedShrug.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/TiredSleepy.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/TongueTease.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/UnSureSuspicious.png\"  height=\"25\" width=\"25\" />");
emoImg.push("<img class=\"emo_messages\" alt=\"\" src=\"images/emos/HeartLoveValentine.png\"  height=\"25\" width=\"25\" />");
	function convertEMO(msgSend)
	{
		var mgs = msgSend;
		//alert("");
		for(i_emo_img=0;i_emo_img<emo.length;i_emo_img++){
			mgs = mgs.replace(emo[i_emo_img], emoImg[i_emo_img]);	
		}
		return mgs;
	}